"""
Detection service configuration.
Calibration parameters and thresholds that can be tuned without redeployment.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from pathlib import Path

_CALIBRATION_JSON = Path(__file__).parent / "ml" / "models" / "calibration.json"


def _load_calibration_overrides() -> dict:
    """Load calibration.json if it exists, else return empty dict."""
    try:
        if _CALIBRATION_JSON.exists():
            with open(_CALIBRATION_JSON) as f:
                return json.load(f)
    except Exception:
        pass
    return {}


_CALIBRATION_OVERRIDES: dict = _load_calibration_overrides()


@dataclass(frozen=True)
class PlattScalingConfig:
    """Platt scaling (sigmoid calibration) parameters.

    P_calibrated = 1 / (1 + exp(-(a * score + b)))

    Initial values a=-1.5, b=0.5 are starting points.
    Optimise against a held-out validation set using train_calibration.py.
    """
    a: float = float(os.getenv("PLATT_A", str(_CALIBRATION_OVERRIDES.get("platt_a", -1.5))))
    b: float = float(os.getenv("PLATT_B", str(_CALIBRATION_OVERRIDES.get("platt_b", 0.5))))
    enabled: bool = os.getenv("PLATT_ENABLED", "false").lower() == "true"


@dataclass(frozen=True)
class TemperatureScalingConfig:
    """Temperature scaling parameters (logit / T before sigmoid)."""
    temperature: float = float(
        os.getenv("ONNX_TEMPERATURE",
                   str(_CALIBRATION_OVERRIDES.get("temperature", 1.8)))
    )


@dataclass(frozen=True)
class EnsembleConfig:
    """ONNX ensemble weights."""
    distilbert_weight: float = float(
        os.getenv("DISTILBERT_WEIGHT",
                   str(_CALIBRATION_OVERRIDES.get("ensemble_weights", {}).get("distilbert", 0.65)))
    )
    tinybert_weight: float = float(
        os.getenv("TINYBERT_WEIGHT",
                   str(_CALIBRATION_OVERRIDES.get("ensemble_weights", {}).get("tinybert", 0.35)))
    )


@dataclass(frozen=True)
class RecallModeConfig:
    """OR-gate ensemble configuration for improving recall.

    When enabled, the pipeline escalates suspicious content to the next tier
    even if the current tier score is below its own threshold, catching edge
    cases that individual detectors miss.
    """
    enabled: bool = os.getenv("RECALL_MODE", "true").lower() == "true"
    # Minimum tier score to trigger escalation (any tier above this → next tier)
    low_threshold: float = float(os.getenv("RECALL_LOW_THRESHOLD", "0.45"))
    # Soft vote: number of detectors that must agree with score > soft_vote_threshold
    soft_vote_min_detectors: int = int(os.getenv("RECALL_SOFT_VOTE_MIN", "2"))
    soft_vote_threshold: float = float(os.getenv("RECALL_SOFT_VOTE_THRESHOLD", "0.40"))





@dataclass(frozen=True)
class CalibrationConfig:
    """Top-level calibration configuration."""
    platt: PlattScalingConfig = field(default_factory=PlattScalingConfig)
    temperature: TemperatureScalingConfig = field(default_factory=TemperatureScalingConfig)
    ensemble: EnsembleConfig = field(default_factory=EnsembleConfig)
    recall: RecallModeConfig = field(default_factory=RecallModeConfig)

    @classmethod
    def load(cls) -> "CalibrationConfig":
        """Load config from env vars and calibration.json."""
        return cls()



# ─── Category-specific action thresholds (auto-generated by optimize_thresholds.py) ──
# Per-category overrides for ACTION_THRESHOLDS. Categories not listed use global defaults.
CATEGORY_THRESHOLDS: dict[str, dict[str, int]] = {
    "API_KEY": {"warn": 48, "redact": 78, "block": 96},
    "BIAS": {"warn": 48, "redact": 78, "block": 96},
    "CREDENTIALS": {"warn": 48, "redact": 78, "block": 96},
    "HALLUCINATION": {"warn": 53, "redact": 78, "block": 96},
    "PII": {"warn": 53, "redact": 78, "block": 96},
    "PROMPT_INJECTION": {"warn": 48, "redact": 78, "block": 96},
    "REGULATORY": {"warn": 53, "redact": 78, "block": 96},
    "SECURITY_VULN": {"warn": 53, "redact": 78, "block": 96},
    "SOURCE_CODE": {"warn": 53, "redact": 78, "block": 96},
}
# ── End category thresholds


# Singleton — import and use directly
CALIBRATION = CalibrationConfig.load()
